export enum Route {
	ButtonTable = "/button-table",
	ColspanHeaderTable = "/colspan-header-table",
	ColspanRowTable = "/colspan-row-table",
	DivTable = "/div-table",
	DuplicateEmptyHeadersTable = "/duplicate-empty-headers-table",
	DynamicLoadTable = "/dynamic-load-table",
	EmptyHeaderRowsTable = "/empty-header-rows-table",
	EmptyBodyRowsTable = "/empty-body-rows-table",
	RowspanHeaderTable = "/rowspan-header-table",
	RowspanRowTable = "/rowspan-row-table",
	SimpleTable = "/simple-table",
	PrimitivesTable = "/primitives-table",
	InnerTextTable = "/inner-text-table",
}
